-- アフィリエイト管理用テーブル
-- minako診断のアフィリエイター毎にLP+LINE誘導URLを管理する
-- Supabase ダッシュボードの SQL Editor で実行してください。

CREATE TABLE IF NOT EXISTS affiliates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  line_url TEXT NOT NULL,
  source TEXT,
  memo TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  site TEXT NOT NULL DEFAULT 'minako',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- slug は site 内でユニーク（marriage_type16 と minako で同じslugを使う想定はないが、安全側）
CREATE UNIQUE INDEX IF NOT EXISTS idx_affiliates_site_slug ON affiliates (site, slug);
CREATE INDEX IF NOT EXISTS idx_affiliates_site ON affiliates (site);
CREATE INDEX IF NOT EXISTS idx_affiliates_is_active ON affiliates (is_active);

COMMENT ON TABLE affiliates IS 'アフィリエイター管理。LPの ?ref=<slug> で参照される。';
COMMENT ON COLUMN affiliates.slug IS 'LP URLの ?ref=<slug> として埋め込まれる識別子（半角英数・ハイフン・アンダースコア）';
COMMENT ON COLUMN affiliates.name IS '管理画面上の表示名（例: さくらさん）';
COMMENT ON COLUMN affiliates.line_url IS 'LP上のLINE登録ボタンの遷移先（アフィリエイター毎の流入経路リンク）';
COMMENT ON COLUMN affiliates.source IS '任意の流入元タグ（instagram / twitter など）';
COMMENT ON COLUMN affiliates.memo IS '任意のメモ';
COMMENT ON COLUMN affiliates.is_active IS '無効化フラグ。falseの場合LPでLINE誘導の代わりに案内表示にしてもよい';

-- updated_at を自動更新するトリガー
CREATE OR REPLACE FUNCTION set_affiliates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_affiliates_updated_at ON affiliates;
CREATE TRIGGER trg_affiliates_updated_at
  BEFORE UPDATE ON affiliates
  FOR EACH ROW
  EXECUTE FUNCTION set_affiliates_updated_at();

-- ============================================================
-- 補足：feature_events に新しい event_type 'lp_line_click' を流す
-- (テーブル構造変更不要。イベントの種類が増えるだけ)
-- payload: { slug, line_url }
-- カラム affiliate_id にも slug を入れて後段集計をしやすくする
-- ============================================================
