-- 恋愛占い・相性診断・診断コード発行のトラッキング用テーブル
-- Supabase ダッシュボードの SQL Editor で実行してください。

CREATE TABLE IF NOT EXISTS feature_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  payload JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_feature_events_event_type ON feature_events (event_type);
CREATE INDEX IF NOT EXISTS idx_feature_events_created_at ON feature_events (created_at DESC);

COMMENT ON TABLE feature_events IS '恋愛占い・相性診断・診断コード発行の管理分析用イベント';
COMMENT ON COLUMN feature_events.event_type IS 'love_fortune | compatibility | diagnosis_code';
COMMENT ON COLUMN feature_events.payload IS '例: diagnosis_code → { "code": "AAA0001", "type": "DPTN" }';
